### PR TITLE
Do not show date, if not set

### PR DESCRIPTION
**Pull request by zeisss**
This allows to hide the date by not providing it in the FrontMatter.

### CODE REVIEW

**Comment by carfesh** [comment]
I really would like that change myself and tried it on my hugo site. As a result I see an issue in the RSS .xml files; the date is set to an odd 01 Jan 0001 for these entries. Do you think it would be possible to correct this?

**Comment by zeisss** [comment]
I have not much experience with hugo, so I am a bit surprised this change influences the RSS generation - any tipp where to look?

**Comment by carfesh** [comment]
I don't have the slightest idea - it may even be a thing that happens in hugo, I could not find a template myself. Maybe it's just not intended for the date to be empty..?

**Comment by zeisss** [comment]
For the RSS feed - pretty sure it must have a date. Maybe we just shouldn't show this date in case of non-posts or sthg.

**Comment by carfesh** [comment]
I'm not sure if they can be excluded from the site's overall XML. For me, I didn't want content to appear in the feed so our RSS link points to the feed for posts only. That may not be feasible for everyone though? That way, all the content was excluded from the XML. It is really a minor thing, but it looks really weird when it occurs.

I have tested it this way on our projects [GitHub page](http://petschau.github.io/WinFellow/). Maybe I will even deploy your change in our next update anyway. I just noticed it and thought it was weird, and I hoped that maybe this can be fixed.

You can see the content pages like About, The Team etc. all have dates which I don't want, and if I apply your change the overall [site XML](http://petschau.github.io/WinFellow/index.xml) has these entries with weird dates.

**Pull request closed without merging**
